### ISSUE TITLE
AT: Increase Test Coverage

### ISSUE THREAD

**Issue by dylanfernandes** [jacobrs/SOEN341#104]
## Task Description
Increase the test coverage that is currently at 75%. Use the coverage report to see what lines are not currently covered by the existing tests in order to write tests to cover those lines.
## Agile Information
**Priority:** medium
**Risk:** Low
**Story Points:** 3

**Comment by MartinSpasov** [comment]
@dylanfernandes Please add a time estimation for this task, aswell as priority and risk!
