### ISSUE TITLE
AT: Write Manual Acceptance Tests for For all UserStories in Sprint 4 

### ISSUE THREAD

**Issue by MartinSpasov** [jacobrs/SOEN341#114]
## Task Description
Using a test template, write down Acceptance tests for All stories in sprint 4 and a few stories in previous sprints. The AT's should cover the Happy path as well as the main wrong paths.
## Task Breakdown
Write ATs for the following Stories from sprint 4:
- [x] #111 
- [x] #44 
- [x] #42
Write ATs for the following Stories from previous sprints:
- [x] #97  
- [x] #90 
- [x] #8  
- [x] #17  
## Agile Information
Priority: High
Risk: none
Time Estimate: 4 Hours

**Comment by pbgnz** [comment]
What does AT mean? Automated Tests or Acceptance Tests?

**Comment by MartinSpasov** [comment]
@pbgnz Acceptance Tests

**Comment by dylanfernandes** [comment]
https://docs.google.com/spreadsheets/d/1FNAWxyDazkzgJEfy0zAQ7T4nYStqu9-tA4cv0fp28uQ/edit#gid=1756110252

Google sheets with the acceptance tests for all our user stories.

**Comment by Philippe229** [comment]
@dylanfernandes #78 is not a user story.
