### ISSUE TITLE
USER: Authentication

### ISSUE THREAD

**Issue by pbgnz** [jacobrs/SOEN341#12]
## User Model
The following properties are necessary for the user model
* firstName (String)
* lastName (String)
* email (String)
* studentId (Number)
* dateAdded (Date)
* lastLogin (Date)
* password (String)
* cuid (String)

## Session Model
The following properties are necessary to link session cookies to server sessions
* sessionId (128 character long String)
* cuid (String relating to user)

**Comment by jacobrs** [comment]
User Login works with passportjs managing the session db.
