### ISSUE TITLE
AT: Write Manual Acceptance Tests for For all UserStories in Sprint 5

### ISSUE THREAD

**Issue by Philippe229** [jacobrs/SOEN341#128]
## Task Description
Using a test template, write down Acceptance tests for All stories in sprint 5. The AT's should cover the Happy path as well as the main wrong paths.

## Task Breakdown
Write ATs for the following Stories from sprint 5:
- [x] Templates for new tests
- [x] #76
- [x] #79
- [x] #127 
 
## Agile Information
Priority: High
Risk: none
Time Estimate: 4 Hours

**Comment by dylanfernandes** [comment]
Google sheets with all the manual tests for user stories (tests in seperate tabs): https://docs.google.com/spreadsheets/d/1FNAWxyDazkzgJEfy0zAQ7T4nYStqu9-tA4cv0fp28uQ/edit#gid=1756110252
