### ISSUE TITLE
BUG: After creating a study group, redirect to profile page

### ISSUE THREAD

**Issue by Philippe229** [jacobrs/SOEN341#129]
### Description
After creating a study group, a user wants to be redirected to the profile page

### Steps to Reproduce
* Click "Create study group"
* Fill the form
* Click "Create study group!" at the bottom

### Agile Information
**Risk:** low
**ETA:** 30 minutes
**Priority:** low

**Comment by pbgnz** [comment]
Olivier tell me if you need help for this
