### ISSUE TITLE
Setup and define roles

### ISSUE THREAD

**Issue by MartinSpasov** [jacobrs/SOEN341#14]
Discuss with the team and try and define roles 

-    **Designer:** Sam
-    **Front-end:** Simon, Sam
-    **Back-end:** Philippe, Pablo, Dylan
-    **Team lead:** Martin
-    **Technical lead:** Jacob
-    **Testers:** everyone

Points: 1

**Comment by jacobrs** [comment]
Is this complete? @MartinSpasov

**Comment by ONourry** [comment]
Is there any role that needs more work than others? I'll fill wherever I am needed.

**Comment by jacobrs** [comment]
| Role           | Team Member     |
|----------------|-----------------|
| Front End      | Samantha, Simon |
| Back End       | Dylan, Philippe, Pablo |
| Team Lead      | Martin          |
| Technical Lead | Jacob           |
| Designer       | Samantha        |
| Testing        | Everyone        |

**Comment by MartinSpasov** [comment]
Added myself to front end aswell to your list, if anyone wants to switch at some point there shouldn't be any issues with it
