### ISSUE TITLE
USER: Registration Page

### ISSUE THREAD

**Issue by jacobrs** [jacobrs/SOEN341#17]
##  Registration Required fields
* Full Name
* Email field
* Student ID
* Password field
* Sign up button (Empty action until the API for registration is complete)
* Sign In button (Link to the login page `/`)
### UI Requirements
* Logo of the application (graduation cap) should be displayed
* The blue background (#446CB3) with white text
* Bootstrap Components
* Responsive Design

### Route/URL
> http://localhost:8000/register

**Comment by jacobrs** [comment]
@ONourry this issue looks like it can be closed

**Comment by ONourry** [comment]
Agreed

**Comment by dylanfernandes** [comment]
https://docs.google.com/spreadsheets/d/1FNAWxyDazkzgJEfy0zAQ7T4nYStqu9-tA4cv0fp28uQ/edit#gid=1984352592
Result of a happy path AT for this UserStory. No sad path is feasible for this UserStory.
