### ISSUE TITLE
Course lists

### ISSUE THREAD

**Issue by MartinSpasov** [jacobrs/SOEN341#26]
Once the User Profile is complete. We need to implement the ability for students to add which courses they are registered to. We can implement a system that will show classes based on what otehrs have entered previously.

**Comment by pbgnz** [comment]
So the students are their classes manually, or is there a list of all classes (probably from an API) ?

**Comment by dylanfernandes** [comment]
Maybe we can make the TA validate if the student is in the class?

**Comment by MartinSpasov** [comment]
@pbgnz We can have a self building database, whenever a student enters a class it will then appear to others
@dylanfernandes There are issues that migh arrise from that, such as if we have diffrent TAs yet i want to join your SG. Unless customer specifies, I dont think we need a filter to make sure enrolled students are actually in the class. Someone might want to join a class for the fun of learning
