### ISSUE TITLE
Study group page

### ISSUE THREAD

**Issue by MartinSpasov** [jacobrs/SOEN341#27]
A page should be implemented where students can create and search for study groups.

- There should be an option to create their own SG and one to join existing ones.
- SG can be private or public and are for a single class only.
- Implement a side menu were we can add the different options for the SG

**Comment by pbgnz** [comment]
This can be done as soon as #95 gets merged. There is no private/public feature though.

**Comment by pbgnz** [comment]
Is this doable?
