### ISSUE TITLE
SG chat/forums

### ISSUE THREAD

**Issue by MartinSpasov** [jacobrs/SOEN341#28]
Every study group should have its own forums and/or live chat.
- Posting on the forum will display your username and picture, clicking on it will redirect to your profile
- Ability to insert basic emojis
- Search feature for the forums
- Attach documents to posts

Live chat is optional, we should discuss with client to see if it has any added value

**Comment by pbgnz** [comment]
I think the live chat (with user, time and redirect) is the minimum feature. 

The rest of the features are enhancements and should be done on Sprint 4 or 5 if there is time left.
