### ISSUE TITLE
Users do not get redirected to the profile page on successful log in

### ISSUE THREAD

**Issue by simon-bourque** [jacobrs/SOEN341#31]
When I log in I do not get redirected to the profile page, instead I get this error message printed to the console: `UserActions.js?a266:31 SyntaxError: Unexpected token U in JSON at position 0`

repo steps:
1. register a new account
2. navigate back to the login screen
3. enter correct email and password
4. click login button

**Comment by jacobrs** [comment]
@simon-bourque just tried to replicate it. I'll need more precise steps cause it worked. Can you provide specific data?

**Comment by simon-bourque** [comment]
1. run mongod from cmd
2. run npm start from cmd
3. open web browser and connect to localhost:8000
4. click Don't have an account... link
5. fill in registration form
6. click register button
7. click Already have an account... link
8. enter correct information into login form
9. click log in button
10. observe nothing happens and open console

web browser: Google Chrome
os: Windows 10
mongodb version: 3.4.1
npm version: 4.0.5
nodejs version: 7.4.0

full console output:
(unknown) Download the React DevTools for a better development experience: https://fb.me/react-devtools
(unknown) [HMR] Waiting for update signal from WDS...
cdn.fontawesome.com/js/stats.js:1 Font Awesome CDN reporting has been enabled
(unknown) [HMR] connected
(unknown) Object
http://localhost:8000/api/users Failed to load resource: the server responded with a status of 403 (Forbidden)
http://localhost:8000/api/users/login Failed to load resource: the server responded with a status of 401 (Unauthorized)
(unknown) SyntaxError: Unexpected token U in JSON at position 0
(unknown) Array[1]


If someone else could try to replicate it that would be great so we can figure out if its an actual bug or something wrong on my side

**Comment by simon-bourque** [comment]
Could this be related to #32?

**Comment by jacobrs** [comment]
@simon-bourque no it's not related to #32, what I'm not understanding is why you get 403 on `api/users/` I tried replicating this like 4 times with no success, what are you feeding the forms? Also if you inspect the collections, is your users collection populated?

**Comment by simon-bourque** [comment]
yes

{ "_id" : ObjectId("588b926df0559b17401fbe61"), "firstName" : "Jacob", "lastName" : "Gagne", "email" : "", "cuid" : "cikqgkv4q01ck7453ualdn3hd", "studentId" : 0 "l
astLogin" : null, "dateAdded" : ISODate("2017-01-27T18:33:17.216Z"), "__v" : 0 }

{ "_id" : ObjectId("5890c7f9b32cff21c459bdf2"), "cuid" : "ciylslptu0000o4ybk3mgbidz", "firstName" : "Simon", "lastName" : "Bourque", "studentId" : 0, "email" : "",
"lastLogin" : null, "dateAdded" : ISODate("2017-01-31T17:23:05.340Z"), "__v" : 0 }

{ "_id" : ObjectId("5891e83fef8eb116fca234bd"), "cuid" : "ciyn0jgti0000jgybalzp9k39", "firstName" : "Simon", "lastName" : "Bourque", "studentId" : 0, "email" : "",
"password" : "3627909a29c31381a071ec27f7c9ca97726182aed29a7ddd2e54353322cfb30abb9e3a6df2ac2c20fe23436311d678564d0c8d305930575f60e2d3d048184d79", "lastLogin" : null, "dateAdded" : ISODate("2017
-02-01T13:53:03.449Z"), "__v" : 0 }

{ "_id" : ObjectId("5891e88cef8eb116fca234be"), "cuid" : "ciyn0l40y0001jgyb47e6a8op", "firstName" : "Bob", "lastName" : "Bobby", "studentId" : 11111111, "email" : "bob@bob.ca", "password" : "3
627909a29c31381a071ec27f7c9ca97726182aed29a7ddd2e54353322cfb30abb9e3a6df2ac2c20fe23436311d678564d0c8d305930575f60e2d3d048184d79", "lastLogin" : null, "dateAdded" : ISODate("2017-02-01T13:54:20
.190Z"), "__v" : 0 }

(I purposely removed email and student id from this comment because repo is public)

The most recent one I made did not show up however, by I've tested it with an account in the db and I still get the issue

**Comment by jacobrs** [comment]
do the passwords have special characters? might be an encoding issue.

**Comment by simon-bourque** [comment]
I just used 12345 lol

**Comment by simon-bourque** [comment]
Id like someone else to try replicating it as well, then we can better see if its an issue with my setup or in the code

**Comment by jacobrs** [comment]
@dylanfernandes @pbgnz

**Comment by simon-bourque** [comment]
btw frequency is 100% for me, it happens everytime, even if I restart everything and attempt to login to an account already existing in the database

**Comment by jacobrs** [comment]
have you tried dropping your users collection?

**Comment by simon-bourque** [comment]
I will try that

**Comment by simon-bourque** [comment]
Yup dropping it did the trick! let everyone know they should remove the old stuff from their db

**Comment by jacobrs** [comment]
@dylanfernandes did it without dropping and it worked for him as well, I removed the dummy data so it won't put stuff in the db on load anymore.

**Comment by dylanfernandes** [comment]
Worked for me once registered but didn't create my account when I entered a bad full name '@123sdfdsf'. We should verify the registration input.
