### ISSUE TITLE
Design: Profile page and Dashboard 

### ISSUE THREAD

**Issue by MartinSpasov** [jacobrs/SOEN341#39]
## Task Description
As a User I want the Dashboard(Profile Page) to look appealing. I want everything to be labeled clearly for easy and intuitive navigation.
## Task Breakdown
- [x] Create a design page for the profile component, dashboard and navigation bar
- [x] The profile component should have the following items
- Profile picture
- Name
- Email
- Student ID
- Currently enrolled classes

## Agile Information
Priority: urgent
Risk: low
Story points: 3

**Comment by samantha-kerr** [comment]
<img width="958" alt="dashboard" src="https://cloud.githubusercontent.com/assets/14853611/22613770/3192e2a6-ea49-11e6-9b47-631ed8082f9b.png">

Here's a look at the initial dashboard page design.
Profile information on the left, calendar and event listings on the right, and main content in the center.
The links in the navigation bar can be general links, and those in the content are user specific.

Feedback?
