### ISSUE TITLE
USERSTORY: Update information in profile page 

### ISSUE THREAD

**Issue by MartinSpasov** [jacobrs/SOEN341#42]
## Task Description
As a user , I want to have the ability to edit my information under my profile page.

## Task Breakdown
- [x] Have an edit information button on the profile page which will redirect you to an edit page
- [x] Edit page should allow you to change your information and use the validation on #44 

## Agile Information
Priority: low
Risk: low
Story points: 3

**Comment by pbgnz** [comment]
Tell me if you encounter any issues with the update api

**Comment by jacobrs** [comment]
@pbgnz you need to merge your update API into master

**Comment by pbgnz** [comment]
Not blocked anymore

**Comment by dylanfernandes** [comment]
https://docs.google.com/spreadsheets/d/1FNAWxyDazkzgJEfy0zAQ7T4nYStqu9-tA4cv0fp28uQ/edit#gid=1312696665
Result of a happy path AT for this UserStory.

**Comment by dylanfernandes** [comment]
https://docs.google.com/spreadsheets/d/1FNAWxyDazkzgJEfy0zAQ7T4nYStqu9-tA4cv0fp28uQ/edit#gid=1744914170
Result of a sad path AT for this UserStory.
