### ISSUE TITLE
Implement Backend API for profile page

### ISSUE THREAD

**Issue by MartinSpasov** [jacobrs/SOEN341#43]
Profile page #41 should grab its information from the backend API 

- The API should fetch logged in user information from the server and update the user information in the redux store (which is used in the front end).

Story points: 3

**Comment by MartinSpasov** [comment]
Discription is vague, dont know specification for the processe @jacobrs @Philippe229  if you can update it with more precise info it will be cool!

**Comment by Philippe229** [comment]
Blocked by #32 and #53

**Comment by simon-bourque** [comment]
#53 is only front end though

**Comment by simon-bourque** [comment]
What do you need from #53?

**Comment by Philippe229** [comment]
Confusion in requirements: On every render call, API should fetch logged in user information from the server and update the user information in the redux store.

**Comment by pbgnz** [comment]
Phil do you need help from me for this issue?

**Comment by simon-bourque** [comment]
Is this the same as #54 and #20??

**Comment by Philippe229** [comment]
Confirmed with @pbgnz duplicate

**Comment by Philippe229** [comment]
Confirmed with @pbgnz duplicate
