### ISSUE TITLE
Set up Server

### ISSUE THREAD

**Issue by MartinSpasov** [jacobrs/SOEN341#50]
Set up a server on which we can host the website

- Use Free Amazon server or purchase server
- Set up a DNS with a nice URL
- Host website on server 

Story points: 2

**Comment by jacobrs** [comment]
Server is up but no source code is there yet, working on the continuous deployment issue now, #51

**Comment by jacobrs** [comment]
Server is up on http://teamstudy.ca/ still need to do some work for the continuous deployment #51.
