### ISSUE TITLE
Set up Continuous Deployment

### ISSUE THREAD

**Issue by MartinSpasov** [jacobrs/SOEN341#51]
Set up Travis for continuous deployment

Story points: 5

**Comment by MartinSpasov** [comment]
@jacobrs Please add more details to the story if you judge clarifications are required

**Comment by jacobrs** [comment]
No acceptance tests written for this. The following steps were performed to verify the functioning of this:

* Deployed github source from the console without hooks
* Deployed the source code with the hooks
* Tested the hooks a second time to ensure deployment success through the console
