### ISSUE TITLE
BUG: Error message displaying on first login attempt.

### ISSUE THREAD

**Issue by ONourry** [jacobrs/SOEN341#70]
Currently, if the user enters the right credentials on his first try, he will see an error message for a split second before being redirected to the profile page. If the user fails on his first try or logins, disconnects and then re-logins then this issue does not happen.  This is due to the user object being created after the submission of the form to the server.

**Comment by jacobrs** [comment]
The error message doesn't pop up anymore, think it was reversed in this commit: 24f458e6f7fd68eff1d0bc9bc8cff97ca93ca134

**Comment by MartinSpasov** [comment]
@ONourry  @jacobrs Can someone please confirm this bug is indeed invalid at this point?

**Comment by Philippe229** [comment]
@MartinSpasov just entered my credentials on the website. No error. Anyone else?

**Comment by MartinSpasov** [comment]
I dont notice anything either, I guess the bug was solved in the commit mentioned by jacob
