### ISSUE TITLE
USER: Login Page

### ISSUE THREAD

**Issue by Philippe229** [jacobrs/SOEN341#8]
##  Login Page Required field
* Email field
* Password field
* Sign In button (Empty action until the API for login complete)
* Sign up button (Links to Registration Page)
### UI Requirements
* Logo of the application (graduation cap) should be displayed
* The blue background (#446CB3) with white text
* Bootstrap Components
* Responsive Design

### Route/URL
> http://localhost:8000/ (the login page acts as the home/landing page)

**Comment by jacobrs** [comment]
@samantha-kerr why the reopening of this issue?

**Comment by samantha-kerr** [comment]
Closing!

**Comment by dylanfernandes** [comment]
https://docs.google.com/spreadsheets/d/1FNAWxyDazkzgJEfy0zAQ7T4nYStqu9-tA4cv0fp28uQ/edit#gid=1756110252
Result of a happy path AT for this UserStory. No sad path is feasible for this UserStory.
