### ISSUE TITLE
USERSTORY: New Loading Icon

### ISSUE THREAD

**Issue by jacobrs** [jacobrs/SOEN341#81]
## Task Description
As a user, I would like to have a more appealing loading screen.

## Task Breakdown
- [x] Design a more visually appealing loading screen that fits with the theme
- [x] Replace current loading screen with the new one

## Agile Information
Priority: low
Risk: low
Story points: 1

**Comment by MartinSpasov** [comment]
@ONourry  Since this is mainly a design story, do you believe @samantha-kerr would be more suited for this?

**Comment by jacobrs** [comment]
I'm done just fixing another issue in that PR.
