### ISSUE TITLE
USER: Profile Page

### ISSUE THREAD

**Issue by Philippe229** [jacobrs/SOEN341#9]
##  Profile Page Required FrontEnd Information
* Username
* Full Name
* StudentId (Only shown if on your own profile)
* Email (Links to a mailto action)
### UI Requirements
* Logo of the application (graduation cap) should be displayed top left in nav bar
* The nav bar should be (#446CB3) with white text
* The background of the content should be white.
* Bootstrap Components
* Responsive Design

### Route/URL
> http://localhost:8000/profile
> http://localhost:8000/profile/username (links to other users' profiles)

**Comment by simon-bourque** [comment]
Can we move this info into #39?

**Comment by jacobrs** [comment]
@simon-bourque agreed!

**Comment by MartinSpasov** [comment]
The design choices should be left to the discretion of the designer, unless the customer asks for something specific, the rest of the ticket is already covered in #39
