### ISSUE TITLE
USERSTORY: Sign Out Button Functionality

### ISSUE THREAD

**Issue by simon-bourque** [jacobrs/SOEN341#90]
## Task Description
As a user, I need to be able to sign out of my account securely.

## Task Breakdown
- [x] Sign Out button on dashboard
- [x] Upon press, account session must be terminated
## Agile Information
Priority: high  
Risk: low     
Story points: 1

**Comment by simon-bourque** [comment]
Tested using following steps

1. Sign in as any user
2. When dashboard has loaded click the sign out button on the dashboard
3. When redirected to landing page attempt to navigate to teamstudy.ca/profile
4. Observe being redirected back to landing page since no current session exists

**Comment by dylanfernandes** [comment]
<img width="1163" alt="screen shot 2017-03-19 at 9 05 45 pm" src="https://cloud.githubusercontent.com/assets/11564885/24086564/e4ae0b84-0ce7-11e7-952a-6c04e1f16629.png">
Result of a happy path AT for this UserStory. Let me know if you would like me to change or add anything to the presentation of the AT.

**Comment by dylanfernandes** [comment]
https://docs.google.com/spreadsheets/d/1FNAWxyDazkzgJEfy0zAQ7T4nYStqu9-tA4cv0fp28uQ/edit#gid=1966607339
Result of a sad path AT for this UserStory.
