### ISSUE TITLE
BUG: Console Warnings

### ISSUE THREAD

**Issue by jacobrs** [jacobrs/SOEN341#91]
### Description
Following the commit 8240026b108454607c0775ed9535cd08dc5dfa52 I get the following errors in the console when accessing the `/profile` while containing a valid cookie.

### Output
```
(node:87767) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'replace' of undefined
(node:87767) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Steps to Reproduce
* Open the website `localhost:PORT`.
* Notice you have a cookie so then type `localhost:PORT/profile` in your nav bar and hit go.
* Notice the error messages have appeared in your console.

### Agile Information
**Risk:** low
**ETA:** 2 hours
**Priority:** low

**Comment by simon-bourque** [comment]
I've looked into this, it is Node.js that is executing this code and generating these warnings, nothing in front end.  If you are using Visual Studio Code or other similar text editor you can break point it and see when it actually throws these exceptions.  It seems to be as soon as I type localhost:800/p that it throws this warning

**Comment by MartinSpasov** [comment]
Issue too complicated to fix, adds no extra value to user
